theme: jekyll-theme-architect
title: Anand Kumar Ashodhiya
description: Official Biography & Bibliography
show_downloads: false

url: "https://anandkumarashodhiya.github.io"
baseurl: "/anand-kumar-ashodhiya"

plugins:
  - jekyll-sitemap

include:
  - articles
  - articles/*.pdf
  - google36447f783b790ee1.html

exclude:
  - LICENSE
