theme: jekyll-theme-architect

title: Anand Kumar Ashodhiya
description: Official Biography & Bibliography
show_downloads: false

# Required for proper sitemap URLs
url: "https://anandkumarashodhiya.github.io"
baseurl: "/anand-kumar-ashodhiya"

# Google verification file
include:
  - google36447f783b790ee1.html

# Plugins (GitHub Pages supported)
plugins:
  - jekyll-sitemap
